services:
  php:
    build:
      context: .
      dockerfile: Docker/php/Dockerfile
    container_name: autoparts-php
    restart: always
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./logs:/var/log
      - ./Docker/php/php.ini:/usr/local/etc/php/php.ini
    env_file:
      - .env
    networks:
      autoparts_network-php:
        ipv4_address: 192.168.32.11

networks:
  autoparts_network-php:
    name: autoparts_network-php
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.32.0/24
