name: Deploy PHP REST API

on:
  push:
    branches: [ main ]
    paths:
      - '**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H gsa-top.ru >> ~/.ssh/known_hosts

    - name: Test SSH Connection
      run: |
        ssh -i ~/.ssh/id_ed25519 gvaurdin@gsa-top.ru "echo 'SSH connection successful'"

    - name: Setup Docker Network
      run: |
        ssh -i ~/.ssh/id_ed25519 gvaurdin@gsa-top.ru "
          if ! docker network inspect autoparts_network >/dev/null 2>&1; then
            docker network create --driver bridge --subnet=192.168.32.0/20 autoparts_network
          fi
        "

    - name: Deploy PHP API
      run: |
        ssh -i ~/.ssh/id_ed25519 root@gsa-top.ru "
          set -e
          cd /var/www
          if git fetch origin main && git status | grep -q 'behind'; then
            git pull origin main
            docker-compose -f /var/www/docker-compose.yml up -d --build --force-recreate php
            docker ps --filter 'name=autoparts-php'
          else
            echo 'No changes detected, skipping deployment.'
          fi
        "


